def conversation():
    print("Hello, I would like to get to know a litte about you")
    print()
    print("Please answer a few brief questions")
    print()
    print("What is your name?")
    name = input()
    print()
    print(f"{name}, What college are you attending?")
    college = input()
    print()
    print(f"{name}, What high school did you attend?")
    high_school = input()
    print()
    print(f"{name}, Which institution is more fun?")
    institution = input()
    print()
    return name, college, high_school, institution
def main():
    name, college, high_school, institution = conversation()
    print(f"\nIt was nice to speak with you, {name}.")
    print()
    print(f"\nYou are currently attending, {college}.")
    print()
    print(f"\nI learned that your high school's name is {high_school}")
    print()
    print(f"\nYou think {institution} is more fun than {high_school}")
    print()
    print("It was fun getting to know a little about you.")
    print()
    print("Let's do this again!")
if __name__ == "__main__":
    main()
